import type { CompetitionJourneySnapshot } from "./competition-journey.js";

const escapeHtml = (value: unknown): string => String(value ?? "").replace(/[&<>"']/g, (character) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;",
})[character]!);

export function renderCompetitionPortfolio(items: readonly CompetitionJourneySnapshot[]): string {
  const competitions = items.length
    ? items.map((item) => `<li><article><div><span>${escapeHtml(item.status)}</span><h2>${escapeHtml(item.name)}</h2><p>Definition revision ${item.draftVersion} · published revision ${item.publication?.revision ?? "—"}</p><details><summary>Technical identity</summary><code>${escapeHtml(item.id)}</code></details></div><a href="/competitions/${encodeURIComponent(item.id)}">Open Organiser Studio</a></article></li>`).join("")
    : "<li class=\"empty\"><h2>No authoritative competitions yet</h2><p>Create or import one through the connected workbench. Reference examples never appear here.</p></li>";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Competitions · Krateasy</title><style>
:root{font-family:system-ui,sans-serif;color:#17201d;background:#f4f2ec}*{box-sizing:border-box;min-width:0}body{margin:0;overflow-wrap:anywhere}.skip{position:absolute;left:-999px}.skip:focus{left:1rem;top:1rem;background:white;padding:.75rem}:focus-visible{outline:3px solid #c95635;outline-offset:3px}.shell{width:min(72rem,100%);margin:auto;padding:clamp(1rem,4vw,3rem)}header{display:flex;align-items:end;justify-content:space-between;gap:1rem;border-bottom:1px solid #c9cbc5;padding-bottom:1.5rem}h1{font-size:clamp(2rem,6vw,4rem);margin:.25rem 0}.eyebrow{font-size:.75rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#9b3d26}.primary,a{color:#174d3d}.primary{display:inline-flex;align-items:center;min-height:44px;padding:0 1rem;border-radius:.65rem;background:#235546;color:white;text-decoration:none;font-weight:750}ul{list-style:none;padding:0;display:grid;gap:.75rem}article,.empty{background:#fffdf8;border:1px solid #d8d7cf;border-radius:1rem;padding:1.25rem}article{display:flex;align-items:center;justify-content:space-between;gap:1rem}article span{font-size:.75rem;font-weight:800;color:#235546}article h2{margin:.3rem 0}p{color:#56615c}code{overflow-wrap:anywhere}@media(max-width:40rem){header,article{align-items:start;flex-direction:column}}@media(max-width:20rem){.shell{padding-inline:.7rem}article,.empty{padding:1rem}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}@media(prefers-contrast:more){p{color:#36443d}article,.empty{border:2px solid #17201d}}@media(forced-colors:active){.primary,article,.empty{border:2px solid ButtonText}}@media print{.primary,.skip{display:none}.shell{padding:0}article{break-inside:avoid}}
</style></head><body><a class="skip" href="#main">Skip to competitions</a><main id="main" class="shell" tabindex="-1"><header><div><div class="eyebrow">Organiser Studio</div><h1>Competitions</h1><p>Every competition opens into its authoritative design workspace. Demonstrations are isolated from pilot truth.</p></div><a class="primary" href="/create">Create or import</a></header><ul aria-label="Authoritative competitions">${competitions}</ul></main></body></html>`;
}
