import { renderOrganiserHeader, sharedStyles, type OrganiserContext } from "./design-system.js";
import type { CompetitionGuardPreflight } from "@tournament-os/competition-engine";

const escape = (value: unknown): string => String(value ?? "").replace(/[&<>"']/g, (character) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;",
}[character]!));

export function renderCompetitionGuardPreflight(input: {
  readonly competitionId: string;
  readonly competitionName: string;
  readonly preflight: CompetitionGuardPreflight;
  readonly context?: OrganiserContext;
}): string {
  const { preflight } = input;
  const findings = preflight.detailed.findings.length
    ? preflight.detailed.findings.map((finding) => `<article class="finding"><h3>${escape(finding.ruleId)} · ${escape(finding.severity)}</h3><p>${escape(finding.message)}</p><p><strong>Correction:</strong> ${escape(finding.suggestedCorrection)}</p><p><code>${escape(finding.evidenceHash)}</code></p></article>`).join("")
    : "<p>No Guard findings apply to this exact revision.</p>";
  const rows = preflight.detailed.accounting.contestLedger.map((row) => `<tr><td>${escape(row.divisionId)}</td><td>${escape(row.stageId)}</td><td>${escape(row.poolId ?? "—")}</td><td>${escape(row.round)}</td><td>${row.requiredContestIds.length}</td><td>${row.scheduledContestIds.length}</td><td>${row.contestMinutes}</td><td>${row.turnaroundMinutes}</td></tr>`).join("");
  const sections = preflight.detailed.sections.map((section) => `<li><strong>${escape(section.id)}</strong>: ${escape(section.status)} <code>${escape(section.evidenceHash.slice(0, 16))}</code></li>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(input.competitionName)} · Guard pre-flight</title><style>
  ${sharedStyles}*{box-sizing:border-box;min-width:0}body{margin:0;overflow-wrap:anywhere}.skip{position:absolute;left:-9999px;top:8px;background:#fff;color:#17201d;padding:12px;border:2px solid currentColor}.skip:focus{left:8px}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}main{max-width:1080px;margin:auto;padding:28px 20px 60px}.hero,.panel,.finding{background:#fff;border:1px solid #dce3dc;border-radius:16px;padding:20px;margin:14px 0}.state{font-size:2rem;font-weight:750}.READY{color:#19734a}.BLOCKED{color:#a23b28}.ACKNOWLEDGEMENT_REQUIRED{color:#765200}details summary{cursor:pointer;min-height:44px;display:flex;align-items:center;font-weight:700}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #dce3dc}code{font-size:.78rem;overflow-wrap:anywhere}a{color:#315d4b;min-height:44px;display:inline-flex;align-items:center}@media(max-width:600px){main{padding:18px 12px}.scroll{overflow:auto}th,td{white-space:nowrap}}@media(max-width:320px){main{padding-inline:8px}.hero,.panel,.finding{padding:14px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}@media(prefers-contrast:more){.hero,.panel,.finding{border:2px solid #17201d}}@media(forced-colors:active){.hero,.panel,.finding{border:2px solid CanvasText}}@media print{body{background:#fff}.skip,.back{display:none}main{max-width:none;padding:0}.hero,.panel,.finding{break-inside:avoid;box-shadow:none}}
  </style></head><body><a class="skip" href="#main">Skip to Guard pre-flight</a>${renderOrganiserHeader("preflight", input.context)}<main id="main" tabindex="-1"><a class="back" href="/competitions/${encodeURIComponent(input.competitionId)}">← Published competition</a><header class="hero"><p>Competition Guard · exact revision evidence</p><h1>${escape(input.competitionName)}</h1><div class="state ${escape(preflight.outcome)}">${escape(preflight.outcome.replaceAll("_", " "))}</div><p>${escape(preflight.simple.headline)} ${escape(preflight.simple.action)}</p><p><code>${escape(preflight.guardReportHash)}</code></p></header><details class="panel" open><summary>Detailed evidence</summary><h2>Integrity and operational quality</h2><p>Integrity: <strong>${escape(preflight.detailed.assurance.integrityGrade)}</strong>. Operational quality: <strong>${escape(preflight.detailed.assurance.operationalQuality)}</strong>.</p><ul>${sections}</ul><div class="scroll"><table><caption>Bottom-up contest and minute ledger</caption><thead><tr><th scope="col">Division</th><th scope="col">Stage</th><th scope="col">Pool</th><th scope="col">Round</th><th scope="col">Required</th><th scope="col">Scheduled</th><th scope="col">Contest min</th><th scope="col">Changeover min</th></tr></thead><tbody>${rows}</tbody></table></div><h2>Findings and corrections</h2>${findings}</details><details class="panel"><summary>Technical evidence</summary><dl><dt>Guard version</dt><dd>${escape(preflight.technical.guardVersion)}</dd><dt>Certification</dt><dd><code>${escape(preflight.technical.certificationHash)}</code></dd><dt>Projection</dt><dd><code>${escape(preflight.projectionHash)}</code></dd></dl></details></main></body></html>`;
}
