export const playerHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#14201c"><title>My next match · Krateasy Competitions</title>
<style>
:root{color-scheme:light;--ink:#17201d;--muted:#65706b;--canvas:#f3f2ed;--surface:#fffefb;--line:#d8d8d1;--accent:#087b59;font-family:Inter,"Avenir Next",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--ink)}.shell{width:min(720px,100%);margin:auto;padding:22px 18px 56px}.top{display:flex;justify-content:space-between;gap:16px;padding-bottom:18px;border-bottom:1px solid var(--line);margin-bottom:34px}.brand{font-weight:850}.verified{font-size:12px;color:var(--accent);font-weight:750;text-align:right}h1{font-size:clamp(38px,10vw,62px);line-height:.95;letter-spacing:-.05em;margin:0 0 12px}.intro,.status,.privacy{color:var(--muted);line-height:1.5}.operation{padding:16px;margin:14px 0;background:#e3f3ed;border-left:5px solid var(--accent);border-radius:12px}.operation strong{display:block;font-size:12px;letter-spacing:.08em;margin-bottom:4px}.operation[data-mode=STOPPED],.operation[data-mode=CANCELLED]{background:#fff0ed;border-color:#a32f22}.identity{margin:26px 0 12px;font-size:14px}.next{background:var(--ink);color:white;border-radius:22px;padding:28px;min-height:300px;display:flex;flex-direction:column;justify-content:space-between;box-shadow:0 18px 50px #17201d1f}.eyebrow{font-size:11px;letter-spacing:.13em;text-transform:uppercase;font-weight:850;color:#73d2b2}.time{font:800 clamp(52px,15vw,82px)/1 ui-monospace,monospace;letter-spacing:-.07em}.next h2{font-size:24px;margin:8px 0}.next p{color:#c9d6d0}.chips{display:flex;gap:8px;flex-wrap:wrap}.chips span{background:#ffffff1c;border-radius:999px;padding:8px 11px;font-size:13px;font-weight:750}.proof{margin-top:18px;background:var(--surface);border:1px solid var(--line);border-radius:15px;padding:16px}.proof code{overflow-wrap:anywhere}.error{display:block;background:#fff0ed;color:#8a2b1f;border-radius:15px;padding:18px}.privacy{font-size:12px;margin-top:18px}@media(max-width:560px){.shell{padding-top:17px}.next{min-height:280px;padding:23px;border-radius:19px}}
</style></head><body><main class="shell"><header class="top"><div class="brand">Krateasy Competitions</div><div class="verified">Signed participant view<br>No app needed</div></header>
<h1>My next match</h1><p class="intro">This private link shows only your current competition identity and the next action from the published schedule and live operational head.</p>
<div id="status" class="status" aria-live="polite">Checking signed access…</div>
<section id="operation" class="operation" aria-live="assertive">Loading event status…</section>
<article class="next" aria-labelledby="next-title"><div><div class="eyebrow" id="next-state">Authoritative next action</div><div class="time" id="next-time">—</div></div><div><h2 id="next-title">Loading</h2><p id="next-opponent">Verifying the current revision.</p><div class="chips"><span id="next-court">Court —</span><span id="report-time">Report —</span></div></div></article>
<section class="proof"><strong id="competition">Competition</strong><p>Projection revision <b id="revision">—</b> · relevant live event <b id="event-sequence">—</b></p><code id="proof">—</code></section>
<p class="privacy">The link is opaque, signed and expiring. It does not expose contact data, the participant directory, eligibility records or another participant’s schedule.</p></main>
<script>
const q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clock=v=>v?new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
async function load(){const params=new URLSearchParams(location.search),competition=params.get('competition'),revision=params.get('revision'),token=params.get('token');if(!competition||!revision||!token){q('#status').innerHTML='<span class="error">This link is incomplete. Ask the organiser for a new signed link.</span>';return}try{const url='/v1/competition-journey/'+encodeURIComponent(competition)+'/participant-next?revision='+encodeURIComponent(revision)+'&token='+encodeURIComponent(token),response=await fetch(url,{cache:'no-store'}),value=await response.json();if(!response.ok)throw Error(value.error||'Access denied');q('#status').textContent=value.participant.displayName+' · '+value.participant.status;q('#operation').dataset.mode=value.operation.mode;q('#operation').innerHTML='<strong>'+esc(value.operation.mode)+' · state '+value.operation.stateVersion+'</strong>'+esc(value.operation.instruction);q('#competition').textContent=value.competition.name;q('#revision').textContent=value.revision;q('#event-sequence').textContent=value.freshness.relevantEventSequence;q('#proof').textContent=value.projectionHash;if(!value.next){q('#next-state').textContent=value.participant.status;q('#next-title').textContent=value.participant.status==='WITHDRAWN'?'No further fixture':'Waiting for confirmation';q('#next-opponent').textContent='The organiser has not published another participant action.';return}q('#next-state').textContent=value.next.status;q('#next-time').textContent=clock(value.next.startsAt);q('#next-title').textContent=value.next.opponent?'vs '+value.next.opponent:'Next fixture';q('#next-opponent').textContent='Fixture '+value.next.contestId;q('#next-court').textContent=value.next.court;q('#report-time').textContent='Report '+clock(value.next.reportingTime)}catch(error){q('#status').innerHTML='<span class="error">The signed view was rejected or is stale. Ask the organiser for the latest link.</span>';q('#operation').className='error';q('#operation').textContent='Authoritative event status unavailable.';q('#next-title').textContent='Unable to show a fixture';q('#next-opponent').textContent=String(error.message||'Access denied')}}load();setInterval(load,15000);
</script></body></html>`;
