import { participantOperationsHtml } from "./attention-views.js";

/** J4 · Live Operation · existing repair preview/approval boundary · Run Control. */
const changeReview = `<section class="card commands" aria-labelledby="change-review-title"><div class="tag">Change Review</div><h2 id="change-review-title">No-show repair</h2><p class="muted">Preview only: the server derives deterministic options from the exact live head and independently Guards them. A separately attributed director approval is required before anything changes.</p><form id="change-review-form"><label>Contest<select id="change-contest"></select></label><label>Absent participant<select id="change-entrant"></select></label><label>Reason<input id="change-reason" value="Absent at call"></label><button class="wide" type="submit">Generate guarded options</button><p class="wide muted" id="change-status" role="status" aria-live="polite"></p><div class="wide" id="change-options"></div></form></section>`;

const changeScript = `<script>
(()=>{const q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let installed=false;function install(){if(installed)return;const form=q('#change-review-form');if(!form)return;installed=true;const load=async()=>{const p=new URLSearchParams(location.search),competition=p.get('competition'),revision=Number(p.get('revision'));if(!competition||!Number.isSafeInteger(revision))return;const r=await fetch('/v1/competition-journey/'+encodeURIComponent(competition)+'/organiser-live?revision='+revision),s=await r.json();if(!r.ok)return;const contests=s.public.contests.filter(x=>x.status==='SCHEDULED'||x.status==='CALLED');q('#change-contest').innerHTML=contests.map(x=>'<option value="'+esc(x.contestId)+'">'+esc(x.contestId+' · '+x.participantNames.join(' vs '))+'</option>').join('');q('#change-entrant').innerHTML=s.participants.map(x=>'<option value="'+esc(x.participantId)+'">'+esc(x.displayName)+'</option>').join('');form.onsubmit=async e=>{e.preventDefault();const status=q('#change-status'),contestId=q('#change-contest').value,entrantId=q('#change-entrant').value;status.textContent='Independently deriving guarded options…';try{const preview=await fetch('/v1/competition-journey/'+encodeURIComponent(competition)+'/no-show-preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expectedRevision:revision,expectedLiveVersion:s.liveVersion,proposalId:'web.no-show.'+crypto.randomUUID(),contestId,entrantId,reason:q('#change-reason').value})}),v=await preview.json();if(!preview.ok)throw Error(v.error);const proposal=v.live?.proposal||v.proposal;const options=proposal?.options||[];q('#change-options').innerHTML=options.map(o=>'<button type="button" data-strategy="'+esc(o.strategy)+'">Approve '+esc(o.strategy.replaceAll('_',' '))+'</button><p class="muted">'+esc((o.consequences||[]).join(' · '))+'</p>').join('');for(const b of q('#change-options').querySelectorAll('button'))b.onclick=async()=>{status.textContent='Submitting the separately approved option…';const a=await fetch('/v1/competition-journey/'+encodeURIComponent(competition)+'/no-show-approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expectedRevision:revision,expectedProposalHash:proposal.proposalHash,strategy:b.dataset.strategy})}),x=await a.json();if(!a.ok){status.textContent='Approval stopped safely. Nothing changed.';return}status.textContent='Approved and published. Reloading Run Control…';location.href='/attention?competition='+encodeURIComponent(competition)+'&revision='+(revision+1)}})}catch(error){status.textContent='Change Review stopped safely. Nothing changed.'}}};load().catch(()=>{});}
document.addEventListener('DOMContentLoaded',install);setTimeout(install,0)})();</script>`;

export const runControlHtml = participantOperationsHtml.replace('<h2 id="participants-title"', `${changeReview}<h2 id="participants-title"`).replace('</body></html>', `${changeScript}</body></html>`);
