import type {CreatorSession} from "./session.js";
import {individualResources,type OperationsEdit} from "./operations.js";
const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const windowRow=(start:string,end:string)=>`<div class="window-row"><label>Start · ISO with offset<input name="start" value="${esc(start)}" required></label><label>End · ISO with offset<input name="end" value="${esc(end)}" required></label><button type="button" data-remove-window>Remove window</button></div>`;
export function renderOperations(session:CreatorSession,host:HTMLElement,onChange:(message:string)=>void){
 const c=session.evaluate().compilation,saved=session.export().operations;
 if(!c.spec||!c.graph){host.innerHTML=saved?'<div class="rules-card"><p>Saved court/duration rules retained. Resolve findings or clear explicitly.</p><button id="clear-operations">Clear saved resource/duration rules</button></div>':"";host.querySelector<HTMLButtonElement>('#clear-operations')?.addEventListener('click',()=>{session.clearOperations();onChange('Saved operational overrides cleared.');});return;}
 const spec=c.spec,graph=c.graph;
 const edit:OperationsEdit=saved??{resources:individualResources(spec),durations:[]};
 const scopes=spec.stages.flatMap(s=>[{stageId:s.id,label:`${s.label} · all rounds`},...Array.from(new Set(graph.nodes.filter(n=>n.stageId===s.id).map(n=>n.round))).map(round=>({stageId:s.id,round,label:`${s.label} · ${round}`}))]);
 host.innerHTML=`<details class="rules-card"><summary>Court windows & contest durations</summary><p class="hint">These are draft resource commitments and rules. No schedule has been generated. Use complete dates with UTC offsets; multiple windows create a break.</p>${edit.resources.map((r,i)=>`<details><summary>Court ${i+1} · ${r.availability.length} windows</summary><form data-court="${i}"><div data-windows>${r.availability.map(w=>windowRow(w.start,w.end)).join("")}</div><button type="button" data-add-window>Add availability window</button><button type="submit">Apply court windows</button></form></details>`).join("")}<form id="duration-form"><label>Stage / round<select name="scope">${scopes.map((s,i)=>`<option value="${i}">${esc(s.label)}</option>`).join("")}</select></label><label>Contest minutes<input name="minutes" type="number" min="1" max="240" value="30" required></label><label>Turnaround minutes<input name="turnaround" type="number" min="0" max="120" value="0" required></label><button type="submit">Apply duration</button></form><ul>${edit.durations.map((d,i)=>`<li>${esc(d.stageId)} · ${esc(d.round??"all rounds")}: ${d.contestMinutes} min + ${d.turnaroundMinutes} turnaround <button data-remove-duration="${i}">Remove override</button></li>`).join("")}</ul>${saved?'<button id="clear-operations">Clear saved resource/duration rules</button>':""}</details>`;
 const report=(r:ReturnType<CreatorSession["setOperations"]>)=>onChange(r.status==="COMMITTED"?"Resource rules updated; review was cleared. Schedule feasibility is not yet checked.":r.message);
 host.onclick=event=>{const target=event.target as HTMLElement;if(target.matches('[data-remove-window]'))target.closest('.window-row')!.remove();};
 host.querySelectorAll<HTMLFormElement>('[data-court]').forEach(form=>{
  form.querySelector('[data-add-window]')!.addEventListener('click',()=>form.querySelector('[data-windows]')!.insertAdjacentHTML('beforeend',windowRow("","")));
  form.onsubmit=event=>{event.preventDefault();const next=structuredClone(edit),data=new FormData(form),starts=data.getAll('start'),ends=data.getAll('end');next.resources[Number(form.dataset.court)]!.availability=starts.map((start,i)=>({start:String(start),end:String(ends[i])}));report(session.setOperations(next));};
 });
 host.querySelector<HTMLFormElement>('#duration-form')!.onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget as HTMLFormElement),scope=scopes[Number(data.get('scope'))]!;const next=structuredClone(edit),round='round' in scope?scope.round:undefined;next.durations=next.durations.filter(d=>d.stageId!==scope.stageId||d.round!==round);next.durations.push({stageId:scope.stageId,...(round===undefined?{}:{round}),contestMinutes:Number(data.get('minutes')),turnaroundMinutes:Number(data.get('turnaround'))});report(session.setOperations(next));};
 host.querySelectorAll<HTMLButtonElement>('[data-remove-duration]').forEach(b=>b.onclick=()=>{const next=structuredClone(edit);next.durations.splice(Number(b.dataset.removeDuration),1);report(session.setOperations(next));});
 host.querySelector('#clear-operations')?.addEventListener('click',()=>report(session.clearOperations()));
}
