import type {CreatorSession} from "./session.js";
import {contestIdentity} from "./plan-locks.js";
const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export function renderPlanLocks(session:CreatorSession,host:HTMLElement,onChange:(message:string)=>void){
 const {interpretation,compilation:c}=session.evaluate(),locks=session.export().planLocks,nodes=c.graph?.nodes.filter(n=>n.kind==="contest")??[];
 host.innerHTML=`<details class="rules-card"><summary>Protected start times · ${locks.length} locked</summary><p class="hint">Plan choices bound to exact contest identities. These pin a start time, not a court. Remaining contests are unscheduled; a full feasibility check comes later.</p>${nodes.length?`<form id="start-lock-form"><label>Contest<select name="contest">${nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.id)} · ${esc(n.round)}</option>`).join("")}</select></label><label>Start · ISO with offset<input name="start" value="${esc(c.spec!.scheduling.start)}" required></label><button type="submit">Lock draft start time</button></form>`:'<p class="hint">Resolve the definition findings to select a contest. Existing locks remain protected.</p>'}<ul>${locks.map(l=>`<li>${esc(l.contestId)}<br>${esc(l.start)} <button data-unlock="${esc(l.contestId)}">Unlock</button></li>`).join("")}</ul></details>`;
 const report=(r:ReturnType<CreatorSession["setStartLock"]>)=>onChange(r.status==="COMMITTED"?"Draft plan lock updated; review was cleared.":r.message);
 host.querySelector<HTMLFormElement>('#start-lock-form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget as HTMLFormElement),node=nodes.find(n=>n.id===data.get('contest'))!;report(session.setStartLock({contestId:node.id,identityHash:contestIdentity(node,c.graph!,c.spec!,interpretation.roster),start:String(data.get('start'))}));});
 host.querySelectorAll<HTMLButtonElement>('[data-unlock]').forEach(b=>b.onclick=()=>report(session.removeStartLock(b.dataset.unlock!)));
}
