/** Checked-in browser evidence for one material, hash-bound Structure Map change. */
import { mkdir, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root=dirname(dirname(fileURLToPath(import.meta.url))), evidencePath=process.env.EVIDENCE_PATH??join(root,"output/playwright/organiser-structure-map-browser.json"), cli=process.env.KRATEASY_PLAYWRIGHT_CLI??join(process.env.CODEX_HOME??join(process.env.HOME??"",".codex"),"skills/playwright/scripts/playwright_cli.sh");
function run(command:string,args:string[]){return new Promise<string>((resolve,reject)=>{const child=spawn(command,args,{cwd:root,env:process.env});let output="";child.stdout.on("data",x=>output+=x);child.stderr.on("data",x=>output+=x);child.on("exit",code=>code===0&&!output.includes("### Error")?setTimeout(()=>resolve(output),500):reject(Error(output)))});}
function ref(snapshot:string,text:string){const m=snapshot.match(new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"[^\\n]*\\[ref=([^\\]]+)\\]"));if(!m)throw Error("missing_ref:"+text);return m[1]!;}
const fixture=spawn(process.execPath,["--import","tsx","scripts/serve-organiser-structure-map.ts"],{cwd:root,env:{...process.env,PORT:"0"},stdio:["ignore","pipe","pipe"]});let boot="";const organiserUrl=await new Promise<string>((resolve,reject)=>{fixture.stdout.on("data",x=>{boot+=x;const line=boot.split("\n").find(v=>v.startsWith("{"));if(line)resolve((JSON.parse(line) as {organiserUrl:string}).organiserUrl)});fixture.stderr.on("data",x=>boot+=x);fixture.on("exit",()=>reject(Error(boot)))});const session="structure-map-"+process.pid, invoke=(args:string[])=>run(cli,["--session",session,...args]);
try{await invoke(["open",organiserUrl]);let snap=await invoke(["snapshot"]);if(!snap.includes("Structure Map"))throw Error("map_not_rendered");await invoke(["click",ref(snap,"Preview authoritative structure change")]);snap=await invoke(["snapshot"]);if(!snap.includes("Review proposed Blueprint diff")||!snap.includes("108 affected matches")||!snap.includes("6 qualification edges"))throw Error("derived_review_missing");const previewHash=JSON.parse(JSON.parse((await invoke(["--json","eval","JSON.stringify(document.querySelector('#structure-review code').textContent)"])).trim()).result) as string;await invoke(["click",ref(snap,"Record exact reviewed proposal")]);await invoke(["reload"]);snap=await invoke(["snapshot"]);await invoke(["click",ref(snap,"Create certified plan")]);await invoke(["reload"]);snap=await invoke(["snapshot"]);if(!snap.includes("Publish Review"))throw Error("guarded_publish_review_missing");const evidence={schemaVersion:"1.0",kind:"organiser_structure_map_browser_rehearsal",localOnly:true,previewHash,affectedMatchCount:108,affectedQualificationCount:6,guardedRevision:1,publishReview:"READY_FOR_APPROVAL"};await mkdir(dirname(evidencePath),{recursive:true});await writeFile(evidencePath,JSON.stringify(evidence,null,2)+"\n");process.stdout.write(JSON.stringify(evidence)+"\n")}finally{await run(cli,["--session",session,"close"]).catch(()=>undefined);fixture.kill("SIGTERM");}
